name: Cypress Tests (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node18.12.0-chrome107

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Prepare folders
        run: |
          mkdir -p cypress/screenshots
          mkdir -p cypress/reports
          chmod -R 777 cypress/screenshots
          chmod -R 777 cypress/reports

      - name: Run Cypress tests
        run: npx cypress run --e2e --browser chrome
        continue-on-error: true
            
      - name: Upload Cypress HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: |
            cypress/reports
            cypress/screenshots
